version: "3.7"

services:
  app:
    container_name: eduhub-app
    build: .
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - .env.prod
  db:
    platform: linux/amd64
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3306:3306

  adminer:
    platform: linux/amd64
    image: adminer
    restart: always
    ports:
      - 8080:8080
